# Generated by Django 3.0.5 on 2021-01-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210110_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Delivered', 'Delivered'), ('out for delivery', 'out for delivery')], max_length=100, null=True),
        ),
    ]
