# Generated by Django 3.0.5 on 2021-01-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210110_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('out for delivery', 'out for delivery'), ('Delivered', 'Delivered'), ('pending', 'pending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='catogory',
            field=models.CharField(choices=[('indoor', 'indoor'), ('OUT DOOR', 'OUT DOOR')], max_length=100, null=True),
        ),
    ]
